@startuml
    !theme plain
    hide empty methods

    !procedure $schema($name, $slug)
        package "$name" as $slug <<Rectangle>>
    !endprocedure

    !procedure $table($name, $slug)
        entity "<b>$name</b>" as $slug << (T, DodgerBlue) >>
    !endprocedure

    !procedure $importtable($name, $slug)
        entity "<b>$name</b>" as $slug << (T, Yellow) >>
    !endprocedure

    !procedure $pk($name)
        <color:#GoldenRod><&key></color> <b>**$name**</b>
    !endprocedure

    !procedure $fk($name)
        <color:#Silver><&key></color> **$name**
    !endprocedure

    !procedure $uk($name)
        {field} <back:#Yellow> <color:#White><&media-record></color> **$name**
    !endprocedure

    !procedure $column($name)
        {field} <color:#White><&media-record></color> **$name**
    !endprocedure

    title "Data warehouse"

    $schema("dwh", "dwh") {
        $importtable("order_info", "order_info") {
            $pk("order_id"):            INTEGER
            $column("customer_id"):     VARCHAR(255)
            $column("salesperson_id"):  VARCHAR(255)
            $column("updated_dtm"):     TIMESTAMP
        }
        $importtable("orderline", "orderline") {
            $pk("orderline_id"):        INTEGER
            $column("order_id"):        INTEGER
            $column("product_id"):      INTEGER
            $column("quantity"):        REAL
            $column("price"):           REAL
        }
        $importtable("customer", "customer") {
            $pk("customer_id"):     VARCHAR(255)
            $column("cust_name"):   VARCHAR(255)
            $column("street"):      VARCHAR(255)
            $column("city"):        VARCHAR(255)
            $column("itn"):         VARCHAR(255)
            $column("updated_dtm"): TIMESTAMP
        }
        $importtable("product", "product") {
            $pk("product_id"):          INTEGER
            $column("product_name"):    VARCHAR(255)
            $column("updated_dtm"):     TIMESTAMP
        }
        $importtable("salesperson", "salesperson") {
            $pk("salesperson_id"):          VARCHAR(255)
            $column("salesperson_name"):    VARCHAR(255)
            $column("updated_dtm"):         TIMESTAMP
        }
        $table("fact_orderline", "fact_orderline") {
            $column("order_date_key"):          DATE
            $column("time_key"):                TIME
            $column("product_key"):             INTEGER
            $column("customer_key"):            INTEGER
            $column("salesperson_key"):         INTEGER
            $column("order_id"):                INTEGER
            $column("orderline_id"):            INTEGER
            $column("quantity"):                REAL
            $column("price"):                   REAL
        }
        $table("dim_customer", "dim_customer") {
            $pk("customer_key"):        INTEGER
            $column("customer_id"):     VARCHAR(255)
            $column("customer_name"):   VARCHAR(255)
            $column("customer_itn"):    VARCHAR(255)
            $column("updated_dtm"):     TIMESTAMP
        }
        $table("dim_product", "dim_product") {
            $pk("product_key"):         INTEGER
            $column("product_id"):      INTEGER
            $column("product_name"):    VARCHAR(255)
            $column("updated_dtm"):     TIMESTAMP
        }
        $table("dim_salesperson", "dim_salesperson") {
            $pk("salesperson_key"):         INTEGER
            $column("salesperson_id"):      VARCHAR(255)
            $column("salesperson_name"):    VARCHAR(255)
            $column("updated_dtm"):         TIMESTAMP
        }
    }
    dwh.customer --> dwh.dim_customer
    dwh.product --> dwh.dim_product
    dwh.salesperson --> dwh.dim_salesperson
    dwh.order_info --> dwh.fact_orderline
    dwh.orderline --> dwh.fact_orderline
    dwh.dim_customer --> dwh.fact_orderline
    dwh.dim_product --> dwh.fact_orderline
    dwh.dim_salesperson --> dwh.fact_orderline
@enduml