#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:projectelster
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:projectelster
    # Absolute path
    #    url: jdbc:h2:C:/projects/projectelster/db/projectelster
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/projectelster/db/projectelster
    # Relative path form current dir
    #    url: jdbc:h2:./db/projectelster
    # Relative path from home
    #    url: jdbc:h2:~/projectelster
    #    tcp: jdbc:h2:tcp://localhost:9092/~/projectelster
    username: sa
    password:

  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: any
      setter: any
      is-getter: any

logging:
  level:
    root: WARN
    org.ikropachev.projectelster: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true