#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      dialect: MySQL8Dialect
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    oltp:
      # ImMemory
      #url: jdbc:h2:mem:projectelster
      #tcp: jdbc:h2:tcp://localhost:9092/mem:projectelster
      #username: sa
      #password:
      # MySQL
      url: jdbc:mysql://localhost:3306/projectelster
      username: root
      password: root
    dwh:
      # ImMemory
      #url: jdbc:hsqldb:mem:projectelster
      #tcp: jdbc:hsqldb:tcp://localhost:9095/mem:projectelster
      #username: sa
      #password:
      # PostgreSQL
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/projectelster
      username: postgres
      password: root
  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: any
      setter: any
      is-getter: any

logging:
  level:
    root: INFO
    org.ikropachev.projectelster: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true